---
- name: Install RHV Manager Packages
  yum:
    name: rhvm
    state: present

- name: Copy Engine-setup answer to /tmp/
  template:
    src: rhvm_answers.conf.j2
    dest: '{{ answer_loc }}'

- name: Perform automated RHV Manager Install
  shell:
    cmd: engine-setup --config-append= '{{ answer_loc }}'
  args:
    executable: /bin/bash
